name: "deploy-flip-forge"
branding:
  icon: book-open
  color: purple
description: "Deploy flip forge on GitHub pages"

inputs:
  file:
    description: "PDF file to convert."
    required: true
  title:
    description: "Page title"
    required: false
    default: "Flip forge"
  backgroundColor:
    description: "Background color"
    required: false
    default: "#000000"
  toolbarColor:
    description: "Toolbar color"
    required: false
    default: "#ffffff"
  description:
    description: "Description of the page"
    required: false
    default: ""
outputs:
  dist:
    description: "Dist folder"
    value: ${{ steps.build.outputs.dist }}

runs:
  using: "composite"
  steps:
    - name: Configure GitHub Pages
      id: configure
      if: ${{ github.token }}
      uses: actions/configure-pages@v5.0.0
    - name: "Install poppler"
      shell: bash
      run: |
        sudo apt update -y
        sudo apt install -y poppler-utils
    - uses: actions/setup-node@v4
      with:
        node-version: "20.x"
    - name: "Install dependencies"
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm ci --omit=optional
        npm run build-action
    - name: "Build site"
      id: build
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm run build-action
