name: "Run Tests"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - uses: ./
        with:
          file: test/lorem_ipsum.pdf
          title: "Lorem Ipsum"
          backgroundColor: "#000000"
          toolbarColor: "#ffffff"
          description: "Test description"
      - run: npm ci
      - id: e2e_tests
        run: env VITE_BASE_URL="/build-flip-forge" npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ failure() && steps.e2e_tests.conclusion == 'failure' }}
        with:
          name: screenshots-and-build
          path: |
            cypress/screenshots/
            dist/
